copyright: ""
name: autorizzazioni
version: 0.0.1
description: Smart contract per gestire le autorizzazioni dei produttori
author: Paglia Francesco
license: ""
repository: https://github.com/Tesi-Magistrale-FP/Nodo_Wasp/tree/main/contracts/wasm/autorizzazioni
events:
    autorizzazioneFornita:
    autorizzazioneRimossa:
structs:
    Autorizzazione:
        concessa: Bool
        idApplicazione: Int32
        idOperazione: Int32
        didConsumatore: String
typedefs:
    ElencoAutorizzazioni: Autorizzazione[]
state:
    autorizzazioni: map[String]ElencoAutorizzazioni
funcs:
    fornisciAutorizzazione:
        params:
            didProduttore: String
            idApplicazione: Int32
            idOperazione: Int32
            didConsumatore: String
    rimuoviAutorizzazione:
        params:
            didProduttore: String
            idApplicazione: Int32
            idOperazione: Int32
            didConsumatore: String
views:
    controllaAutorizzazione:
        params:
            didProduttore: String
            idApplicazione: Int32
            idOperazione: Int32
            didConsumatore: String
        results:
            esitoC: Bool
