copyright: ""
name: mycontract
version: 0.0.1
description: mycontract description
author: ""
license: ""
repository: ""
events: {}
structs: {}
typedefs: {}
state:
    utenti: map[String]String
funcs:
    registrazione:
        params:
            did: String
            password: String
    eliminazione:
        params:
            did: String
            password: String
views:
    login:
        params:
            did: String
            password: String
        results:
            esitoL: Bool
