copyright: ""
name: mycontract2
version: 0.0.2
description: mycontract2 description
author: ""
license: ""
repository: ""
events: {}
structs: {}
typedefs: {}
state:
    prova: String
funcs:
    init:
        params:
            prova: String?
    setProva:
        params:
            prova: String
views:
    getProva:
        results:
            prova: String
