copyright: ""
name: autenticazione
version: 0.0.1
description: Smart contract per gestire l'autenticazione
author: Paglia Francesco
license: ""
repository: https://github.com/Tesi-Magistrale-FP/Nodo_Wasp/tree/main/contracts/wasm/autenticazione
events: 
    registrazioneSuccesso:
    registrazioneFallimento:
    eliminazioneSuccesso:
    eliminazioneFallimento:
structs: {}
typedefs: {}
state:
    utenti: map[String]String
funcs:
    registrazione:
        params:
            did: String
            password: String
    eliminazione:
        params:
            did: String
            password: String
views:
    login:
        params:
            did: String
            password: String
        results:
            esitoL: Bool