copyright: ""
name: mycontract4
version: 0.0.1
description: mycontract4 description
author: ""
license: ""
repository: ""
events: {}
structs: {}
typedefs: {}
state: {}
funcs: {}
views:
    getInfo:
        params:
            netUrl: String
        results:
            info: String